const actionTypes = {
  OPEN_CAMERA: "OPEN_CAMERA",
  CLOSE_CAMERA: "CLOSE_CAMERA",
  TOGGLE_PREVIEW_MENU: "TOGGLE_PREVIEW_MENU",
  LOAD_EDITOR: "LOAD_EDITOR",
  CLOSE_EDITOR: "CLOSE_EDITOR",
  EDIT_PHOTO: "EDIT_PHOTO",
  ADD_EDIT_INDEX: "ADD_EDIT_INDEX",
  REMOVE_EDIT_INDEX: "REMOVE_EDIT_INDEX",
  SET_ALERT_MSG: "SET_ALERT_MSG",
  SET_DOWNLOAD_SETTINGS: "SET_DOWNLOAD_SETTINGS",
  SET_NEW_PHOTOS_ADDED: "SET_NEW_PHOTOS_ADDED",
};

export default actionTypes;
