const actionTypes = {
  OPEN_CAMERA: "OPEN_CAMERA",
  CLOSE_CAMERA: "CLOSE_CAMERA",
  SET_IMAGES: "SET_IMAGES",
  ADD_NEW_PICTURE: "ADD_NEW_PICTURE",
  ADD_EDITED_PICTURE: "ADD_EDITED_PICTURE",
  TOGGLE_PREVIEW_MENU: "TOGGLE_PREVIEW_MENU",
  REMOVE_PHOTO: "REMOVE_PHOTO",
  MOVE_IMAGES: "MOVE_IMAGES",
  IMAGES_UPLOADED: "IMAGES_UPLOADED",
  SET_PREV_IMAGES: "SET_PREV_IMAGES",
  LOAD_EDITOR: "LOAD_EDITOR",
  CLOSE_EDITOR: "CLOSE_EDITOR",
  EDIT_PHOTO: "EDIT_PHOTO",
  ADD_EDIT_INDEX: "ADD_EDIT_INDEX",
  REMOVE_EDIT_INDEX: "REMOVE_EDIT_INDEX",
  SET_ALERT_MSG: "SET_ALERT_MSG",
};

export default actionTypes;
